export enum Errors {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  MISSING_AUTH_TOKEN = 'MISSING_AUTH_TOKEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  UNABLE_TO_GENERATE_KEY_PAIR = 'UNABLE_TO_GENERATE_KEY_PAIR',
  UNABLE_TO_DOWNLOAD_FILE = 'UNABLE_TO_DOWNLOAD_FILE',
  MISSING_PUBLIC_KEY = 'MISSING_PUBLIC_KEY',
  INCORRECT_AUTH_TOKEN_OR_EXPIRED = 'INCORRECT_AUTH_TOKEN_OR_EXPIRED',
  UNABLE_TO_GENERATE_TOKEN = 'UNABLE_TO_GENERATE_TOKEN',
}
